function steamdeck_pacman()
{
  if [[ "${1}" == "" ]]; then
    echo "deck_pacman <enable|disable|status>"
    return 1
  fi

  if [[ "${1}" == "status" ]]; then
    sudo steamos-readonly status
  elif [[ "${1}" == "disable" ]]; then
    sudo steamos-readonly disable
    sudo pacman-key --init
    sudo pacman-key --populate archlinux
    sudo pacman-key --populate holo
  elif [[ "${1}" == "enable" ]]; then
    sudo steamos-readonly enable
  fi
}